### ISSUE TITLE
Get rules in spreadsheets for product-specific global attributes

### ISSUE THREAD

**Issue by agstephens** [ncasuk/amf-check-writer#17]
Put in WARNING for now in code that they are not working yet.

Request BB adds in compliance checking rules in spreadsheets.

**Comment by agstephens** [comment]
Once we have the rules we can add the checks in more YAML files.

But: we probably don't want to put anything in the CVs - because the rules are based on text patterns/restrictions rather than fixed values - i.e. they are not _real_ vocabularies.

**Comment by agstephens** [comment]
@gapintheclouds is this now all working?

**Comment by gapintheclouds** [comment]
Yes, this is working now.
