### ISSUE TITLE
Install compliance-check-lib library and test at python 3.

### ISSUE THREAD

**Issue by agstephens** [ncasuk/amf-check-writer#23]
Install:

https://github.com/cedadev/compliance-check-lib

Initially, we just want the unit tests to run, as outlined here:

https://github.com/cedadev/compliance-check-lib#testing

The tests use lots of test data inside the repository.

**Comment by gapintheclouds** [comment]
@agstephens Installed compliance-check-lib. When I try and run tests, I get errors. Should I have a MANIFEST directory in the pyessv-archive-eg-cvs directory? We can discuss tomorrow.

**Comment by agstephens** [comment]
@gapintheclouds there is a version of the pyessv-archive-eg-cvs directory as a git submodule in the repository. After you have cloned the main repo, I think you need to tell git to pull the submodule (i.e. sub-repository), I think the command is:

```
git submodule update --init --recursive
```

**Comment by gapintheclouds** [comment]
@agstephens Thanks for that. The command worked and pulled in `cc-vocab-cache`, but I still get the error messages.

**Comment by gapintheclouds** [comment]
```
2020-06-23 08:44:14.791517 [INFO] :: PYESSV :: Loading vocabularies from /home/hugo/.esdoc/pyessv-archive:
=============================================================================================== short test summary info ================================================================================================
ERROR checklib/test/test_callable_check_base.py - AssertionError: Invalid authority MANIFEST: /home/hugo/.esdoc/pyessv-archive/pyessv-archive-eg-cvs/MANIFEST
ERROR checklib/test/test_ess_vocabs_checks.py
ERROR checklib/test/test_format_checks.py - AssertionError: Invalid authority MANIFEST: /home/hugo/.esdoc/pyessv-archive/pyessv-archive-eg-cvs/MANIFEST
ERROR checklib/test/test_nc_coords_checks.py - AssertionError: Invalid authority MANIFEST: /home/hugo/.esdoc/pyessv-archive/pyessv-archive-eg-cvs/MANIFEST
ERROR checklib/test/test_nc_file_checks.py
ERROR checklib/test/test_nc_var_checks.py - AssertionError: Invalid authority MANIFEST: /home/hugo/.esdoc/pyessv-archive/pyessv-archive-eg-cvs/MANIFEST
```

**Comment by agstephens** [comment]
All tests now pass on `master` branch - so closing.
