### ISSUE TITLE
Download Barb's training data set and test it with the working version

### ISSUE THREAD

**Issue by agstephens** [ncasuk/amf-check-writer#33]
To generate the training data and run the checker on it all (in a re-runnable way):

https://github.com/barbarabrooks/NCAS-Data-Project-Training-Data

Download, run it locally and it should generate the training data in a local `data/` directory.

**Comment by agstephens** [comment]
See: https://github.com/barbarabrooks/NCAS-Data-Project-Training-Data/pull/1

**Comment by gapintheclouds** [comment]
This works now.
